// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using com.b_velop.XmlRpc.Contexts;

namespace com.b_velop.XmlRpc.Migrations
{
    [DbContext(typeof(HomeContext))]
    [Migration("20190826063023_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079");

            modelBuilder.Entity("com.b_velop.XmlRpc.Models.StateEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("Created");

                    b.Property<string>("Name");

                    b.Property<bool>("State");

                    b.Property<DateTime?>("Updated");

                    b.HasKey("Id");

                    b.ToTable("State");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Created = new DateTime(2019, 8, 26, 8, 30, 23, 293, DateTimeKind.Local).AddTicks(7270),
                            State = false
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
